---
abstract: 'Read from a TAP archive and convert it for displaying'
author:
  - 'Boris Däppen <bdaeppen.perl@gmail.com>, Renée Bäcker <module@renee-baecker.de>'
build_requires:
  Cwd: 0
  TAP::Formatter::HTML: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Convert-TAP-Archive
requires:
  Capture::Tiny: 0
  Exporter: 0
  TAP::Harness: 0
  TAP::Harness::Archive: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/borisdaeppen/Convert-TAP-Archive
  repository: git://github.com/borisdaeppen/Convert-TAP-Archive.git
version: 0.005
